url: http://www.the-tubez.de
baseurl:

# Site settings
title: The Tubez
email: franzi.bopp@gmx.de
description: ""

# Build settings
markdown: kramdown
permalink: pretty

google_static_map_key: AIzaSyCiGMsLV2_mYqcbGRX0I60KmyykmGJEkSc
